{% set name = "Panoply" %}
{% set version = "5.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-{{ version }}.tgz
  sha256: aef277a7201b1c8dbf837bfe78a405d10f66c7afa52e8cda07c08b000cce5d1b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - dos2unix
  run:
    - openjdk >=11

test:
  commands:
    - test -f $PREFIX/bin/panoply
    - test -f $PREFIX/bin/panoply.bat
    - test -f $PREFIX/bin/panoplycl
    - test -f $PREFIX/bin/panoplycl.bat
    - ncj-panoply-ncdump
    - ncj-panoply-nccopy
    - ncj-panoply-nccompare
    - ncj-panoply-bufrspliter
    - ncj-panoply-cfpointwriter
    - ncj-panoply-gribcdmindex
    - ncj-panoply-featurescan
    - ncj-panoply-catalogcrawler


about:
  home: https://www.giss.nasa.gov/tools/panoply/
  summary: Panoply plots geo-referenced and other arrays from netCDF, HDF, GRIB, and other datasets.
  license: Unlicense
  license_file: README.txt
  doc_url: https://www.giss.nasa.gov/tools/panoply/help/
  dev_url: https://www.giss.nasa.gov/tools/panoply/credits.html

extra:
  recipe-maintainers:
    - cofinoa
    - scharlton2
