{% set name = "Panoply" %}
{% set version = "5.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.giss.nasa.gov/tools/panoply/download/PanoplyJ-{{ version }}.tgz
  sha256: 173d48159c2bec4aaaca9b79d27dea6a8463c1fbd2a12de46cc85b8336dcd49e

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk >=11

test:
  commands:
    - test -f $PREFIX/bin/panoply            # [unix]
    - if exist %SCRIPT%\panoply.bat exit 1   # [win]
    - test -f $PREFIX/bin/panoplycl            # [unix]
    - if exist %SCRIPT%\panoplycl.bat exit 1   # [win]
    - ncj-panoply-ncdump
    - ncj-panoply-nccopy
    - ncj-panoply-nccompare
    - ncj-panoply-bufrspliter
    - ncj-panoply-cfpointwriter
    - ncj-panoply-gribcdmindex
    - ncj-panoply-featurescan
    - ncj-panoply-catalogcrawler


about:
  home: https://www.giss.nasa.gov/tools/panoply/
  summary: Panoply plots geo-referenced and other arrays from netCDF, HDF, GRIB, and other datasets.
  license: Unlicense
  license_file: README.txt
  doc_url: https://www.giss.nasa.gov/tools/panoply/help/
  dev_url: https://www.giss.nasa.gov/tools/panoply/credits.html

extra:
  recipe-maintainers:
    - cofinoa
